// Code generated by MockGen. DO NOT EDIT.
// Source: internal/entity/temperature.go
//
// Generated by this command:
//
//	mockgen -source=internal/entity/temperature.go -destination=internal/usecase/temperature/mock/find_temperature.go
//

// Package mock_entity is a generated GoMock package.
package mock_entity

import (
	context "context"
	reflect "reflect"

	entity "github.com/verdade/temperature-by-cep-api/internal/entity"
	temperature "github.com/verdade/temperature-by-cep-api/pkg/temperature"
	gomock "go.uber.org/mock/gomock"
)

// MockFindTemperatureUseCase is a mock of FindTemperatureUseCase interface.
type MockFindTemperatureUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockFindTemperatureUseCaseMockRecorder
}

// MockFindTemperatureUseCaseMockRecorder is the mock recorder for MockFindTemperatureUseCase.
type MockFindTemperatureUseCaseMockRecorder struct {
	mock *MockFindTemperatureUseCase
}

// NewMockFindTemperatureUseCase creates a new mock instance.
func NewMockFindTemperatureUseCase(ctrl *gomock.Controller) *MockFindTemperatureUseCase {
	mock := &MockFindTemperatureUseCase{ctrl: ctrl}
	mock.recorder = &MockFindTemperatureUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFindTemperatureUseCase) EXPECT() *MockFindTemperatureUseCaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockFindTemperatureUseCase) Execute(ctx context.Context, zipCode string) (*temperature.Info, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, zipCode)
	ret0, _ := ret[0].(*temperature.Info)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockFindTemperatureUseCaseMockRecorder) Execute(ctx, zipCode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockFindTemperatureUseCase)(nil).Execute), ctx, zipCode)
}

// MockProxyTemperatureUseCase is a mock of ProxyTemperatureUseCase interface.
type MockProxyTemperatureUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockProxyTemperatureUseCaseMockRecorder
}

// MockProxyTemperatureUseCaseMockRecorder is the mock recorder for MockProxyTemperatureUseCase.
type MockProxyTemperatureUseCaseMockRecorder struct {
	mock *MockProxyTemperatureUseCase
}

// NewMockProxyTemperatureUseCase creates a new mock instance.
func NewMockProxyTemperatureUseCase(ctrl *gomock.Controller) *MockProxyTemperatureUseCase {
	mock := &MockProxyTemperatureUseCase{ctrl: ctrl}
	mock.recorder = &MockProxyTemperatureUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProxyTemperatureUseCase) EXPECT() *MockProxyTemperatureUseCaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockProxyTemperatureUseCase) Execute(ctx context.Context, zipCode string) (*entity.TemperatureInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, zipCode)
	ret0, _ := ret[0].(*entity.TemperatureInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockProxyTemperatureUseCaseMockRecorder) Execute(ctx, zipCode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockProxyTemperatureUseCase)(nil).Execute), ctx, zipCode)
}
